identity:
  assistant_name: Charon
  custom_color: ''
  user_name: Wilson
  voice: Charon
llamacpp:
  gpu_enabled: true
  gpu_layers: 999
ollama:
  gpu_enabled: true
  gpu_layers: -1
voice:
  charon_toolset: full
