import json
import os
import platform
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_CNW: dict = (
    {"creationflags": subprocess.CREATE_NO_WINDOW}
    if platform.system() == "Windows" else {}
)

def _base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


def _get_os() -> str:
    _sys = platform.system()
    if _sys == "Darwin":
        return "mac"
    if _sys == "Linux":
        return "linux"
    return "windows"


def _scripts_dir() -> Path:
    d = Path.home() / ".jarvis" / "reminders"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _sanitise(text: str, max_len: int = 200) -> str:
    return (
        text.replace("\\", "")
            .replace('"', "")
            .replace("'", "")
            .replace("\n", " ")
            .replace("\r", "")
            .strip()
    )[:max_len]

def _write_notify_script(task_name: str, message: str, os_name: str) -> Path:
    script_path = _scripts_dir() / f"{task_name}.py"
    msg_literal = json.dumps(message)  

    if os_name == "windows":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        from win10toast import ToastNotifier
        ToastNotifier().show_toast("J.A.R.V.I.S Reminder", message, duration=15, threaded=False)
        notified = True
    except Exception:
        pass

if not notified:
    try:
        import subprocess
        subprocess.run(["msg", "*", "/TIME:30", message], check=False)
    except Exception:
        pass

try:
    import winsound
    for freq in [800, 1000, 1200]:
        winsound.Beep(freq, 180)
        import time; time.sleep(0.08)
except Exception:
    pass
"""

    elif os_name == "mac":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        script = 'display notification "{{}}" with title "J.A.R.V.I.S Reminder"'.format(
            message.replace('"', '')
        )
        subprocess.run(["osascript", "-e", script], check=False)
    except Exception:
        pass
"""

    else:  # linux
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        subprocess.run(
            ["notify-send", "--urgency=normal", "--expire-time=15000",
             "J.A.R.V.I.S Reminder", message],
            check=False
        )
    except Exception:
        pass
"""

    script_body = f"""# Auto-generated by J.A.R.V.I.S reminder — do not edit
import sys, os, pathlib
{notify_block}
# Self-delete after firing
try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o600)   # owner read/write only
    return script_path

def _schedule_windows(target_dt: datetime, task_name: str,
                      script_path: Path, message: str) -> str:
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>J.A.R.V.I.S Reminder</Description></RegistrationInfo>\n'
        '  <Triggers><TimeTrigger>\n'
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        '    <Enabled>true</Enabled>\n'
        '  </TimeTrigger></Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )

    xml_path.write_text(xml_content, encoding="utf-16")

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True, text=True, **_CNW,
    )

    try:
        xml_path.unlink(missing_ok=True)
    except Exception:
        pass

    if result.returncode != 0:
        script_path.unlink(missing_ok=True)
        err = (result.stderr or result.stdout).strip()
        print(f"[Reminder] ❌ schtasks: {err}")
        return ""  

    return task_name


def _schedule_mac(target_dt: datetime, task_name: str,
                  script_path: Path) -> str:
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    label     = f"com.jarvis.reminder.{task_name}"
    plist_path = agents_dir / f"{label}.plist"

    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{sys.executable}</string>
    <string>{script_path}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Year</key>   <integer>{target_dt.year}</integer>
    <key>Month</key>  <integer>{target_dt.month}</integer>
    <key>Day</key>    <integer>{target_dt.day}</integer>
    <key>Hour</key>   <integer>{target_dt.hour}</integer>
    <key>Minute</key> <integer>{target_dt.minute}</integer>
  </dict>
  <key>RunAtLoad</key>         <false/>
  <key>StandardOutPath</key>   <string>/dev/null</string>
  <key>StandardErrorPath</key> <string>/dev/null</string>
</dict>
</plist>
"""
    plist_path.write_text(plist_content, encoding="utf-8")
    plist_path.chmod(0o644)

    result = subprocess.run(
        ["launchctl", "load", str(plist_path)],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        plist_path.unlink(missing_ok=True)
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ launchctl: {result.stderr.strip()}")
        return ""

    return label


def _schedule_linux(target_dt: datetime, task_name: str,
                    script_path: Path) -> str:

    if shutil.which("systemd-run"):
        on_calendar = target_dt.strftime("%Y-%m-%d %H:%M:00")
        result = subprocess.run(
            [
                "systemd-run",
                "--user",
                f"--on-calendar={on_calendar}",
                f"--unit={task_name}",
                "--",
                sys.executable, str(script_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ⚠️ systemd-run failed: {result.stderr.strip()}, trying 'at'")

    if shutil.which("at"):
        at_time = target_dt.strftime("%H:%M %Y-%m-%d")
        cmd_str = f"{sys.executable} {script_path}\n"
        result  = subprocess.run(
            ["at", at_time],
            input=cmd_str, capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ❌ at: {result.stderr.strip()}")
        return ""

    print("[Reminder] ❌ Neither systemd-run nor at found on this Linux system.")
    return ""

def _persist_reminder(target_dt: datetime, message: str) -> int | None:
    """
    Grava o lembrete no SQLite (via core.reminders).

    Este e o caminho usado em VPS headless, onde schtasks/systemd-run/at
    nao funcionam. O backend dispara na hora certa pelo loop de lembretes.
    Retorna o id, ou None se falhar.
    """
    try:
        from core.reminders import add_reminder
        from core.tenant_identity import get_current_tenant

        return add_reminder(
            fire_at=target_dt,
            message=message,
            tenant_id=get_current_tenant(),
            channel="voice",
        )
    except Exception as e:
        print(f"[Reminder] Falha ao persistir no banco: {e}")
        return None


def reminder(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
) -> str:

    date_str = parameters.get("date", "").strip()
    time_str = parameters.get("time", "").strip()
    message  = parameters.get("message", parameters.get("text", "Reminder")).strip()

    if not date_str and not time_str:
        return "Preciso de uma data e hora para criar o lembrete."

    # HORA LOCAL DO USUARIO, nao do servidor.
    #
    # O VPS roda em UTC. Brasilia e UTC-3, entao as 21h daqui o servidor acha
    # que sao 00h do dia seguinte — e um lembrete pedido para "14:30" parecia
    # ja ter passado. O fuso vem do frontend (campo `timezone`) e chega aqui
    # pelo ContextVar `current_timezone`.
    try:
        from core.tenant_identity import get_current_timezone, now_local

        _tz_nome = get_current_timezone()
        now = now_local(_tz_nome)
    except Exception:
        _tz_nome = "America/Sao_Paulo"
        now = datetime.now()

    print(f"[Reminder] Fuso do usuario: {_tz_nome} | agora local: {now.strftime('%d/%m/%Y %H:%M')}")

    # ── Parsing de linguagem natural ──────────────────────────────────────────
    import re as _re

    def _parse_natural_datetime(date_s: str, time_s: str) -> datetime | None:
        """Tenta interpretar datalangnatural em portugues."""
        dt = None
        combined = f"{date_s} {time_s}".lower().strip()

        # "em X horas/minutos"
        m = _re.search(r'em\s+(\d+)\s*(hora|horas|hrs|hr|minuto|minutos|min)', combined)
        if m:
            qty = int(m.group(1))
            unit = m.group(2)
            if 'min' in unit:
                dt = now + __import__('datetime').timedelta(minutes=qty)
            else:
                dt = now + __import__('datetime').timedelta(hours=qty)
            return dt

        # "amanha", "depois de amanha"
        if 'depois de amanha' in combined or 'depois de amanha' in date_s.lower():
            dt = now + __import__('datetime').timedelta(days=2)
        elif 'amanha' in combined or 'amanha' in date_s.lower():
            dt = now + __import__('datetime').timedelta(days=1)
        elif 'hoje' in combined or 'hoje' in date_s.lower():
            dt = now
        elif 'segunda' in combined:
            days_ahead = (7 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)
        elif 'terca' in combined or 'terça' in combined:
            days_ahead = (1 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)
        elif 'quarta' in combined:
            days_ahead = (2 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)
        elif 'quinta' in combined:
            days_ahead = (3 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)
        elif 'sexta' in combined:
            days_ahead = (4 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)
        elif 'sabado' in combined or 'sábado' in combined:
            days_ahead = (5 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)
        elif 'domingo' in combined:
            days_ahead = (6 - now.weekday()) % 7 or 7
            dt = now + __import__('datetime').timedelta(days=days_ahead)

        if dt is None:
            # Tenta formato YYYY-MM-DD
            try:
                dt = datetime.strptime(f"{date_s} {time_s}", "%Y-%m-%d %H:%M")
                return dt
            except ValueError:
                pass
            # Tenta so hora (hoje)
            try:
                t = datetime.strptime(time_s, "%H:%M").time()
                dt = now.replace(hour=t.hour, minute=t.minute, second=0, microsecond=0)
                if dt <= now:
                    dt += __import__('datetime').timedelta(days=1)
                return dt
            except ValueError:
                pass
            return None

        # Aplica hora se fornecida
        if time_s:
            tm = _re.match(r'(\d{1,2})[h:](\d{2})', time_s)
            if tm:
                dt = dt.replace(hour=int(tm.group(1)), minute=int(tm.group(2)), second=0, microsecond=0)
            else:
                # Tenta HH:MM
                try:
                    t = datetime.strptime(time_s, "%H:%M").time()
                    dt = dt.replace(hour=t.hour, minute=t.minute, second=0, microsecond=0)
                except ValueError:
                    pass
        else:
            # Sem hora, usa proxima hora cheia
            if dt.date() == now.date():
                next_hour = now.hour + 1
                if next_hour > 23:
                    next_hour = 9
                    dt += __import__('datetime').timedelta(days=1)
                dt = dt.replace(hour=next_hour, minute=0, second=0, microsecond=0)

        return dt

    target_dt = _parse_natural_datetime(date_str, time_str)

    if target_dt is None:
        return "Nao consegui entender a data e hora. Use formato YYYY-MM-DD HH:MM ou digite algo como 'amanha as 14:30' ou 'em 2 horas'."

    if target_dt <= now:
        return "Esse horario ja passou — nao posso criar lembrete no passado."

    os_name    = _get_os()
    safe_msg   = _sanitise(message)
    task_name  = f"JARVISReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}"

    # ── 1. Caminho preferido: persistir no banco ─────────────────────────
    # O loop de lembretes do backend dispara na hora certa. Funciona em VPS
    # headless, sobrevive a reboot e e isolado por tenant.
    reminder_id = _persist_reminder(target_dt, safe_msg)

    if reminder_id is not None:
        if player:
            player.write_log(f"[Reminder] ✅ {target_dt.strftime('%d/%m/%Y %H:%M')} — {safe_msg[:40]}")
        dias = ["segunda-feira", "terca-feira", "quarta-feira", "quinta-feira",
                "sexta-feira", "sabado", "domingo"]
        dia_semana = dias[target_dt.weekday()]
        friendly = target_dt.strftime(f"%d/%m/%Y as %H:%M ({dia_semana})")
        return f"Lembrete criado para {friendly}. Vou te avisar!"

    # ── 2. Fallback: agendador do sistema (desktop com UI) ───────────────
    try:
        script_path = _write_notify_script(task_name, safe_msg, os_name)
    except Exception as e:
        return f"Nao consegui preparar o script do lembrete: {e}"

    try:
        if os_name == "windows":
            job_id = _schedule_windows(target_dt, task_name, script_path, safe_msg)
        elif os_name == "mac":
            job_id = _schedule_mac(target_dt, task_name, script_path)
        else:
            job_id = _schedule_linux(target_dt, task_name, script_path)
    except Exception as e:
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ Scheduling exception: {e}")
        return "Algo deu errado ao agendar o lembrete."

    if not job_id:
        return "Nao consegui registrar o lembrete no agendador do sistema."

    if player:
        player.write_log(f"[Reminder] ✅ {target_dt.strftime('%d/%m/%Y %H:%M')} — {safe_msg[:40]}")

    dias = ["segunda-feira", "terca-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sabado", "domingo"]
    dia_semana = dias[target_dt.weekday()]
    friendly = target_dt.strftime(f"%d/%m/%Y as %H:%M ({dia_semana})")
    return f"Lembrete criado para {friendly}. Vou te avisar!"